name: deploy-docker

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: docker login
        run: |
          docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} 
      - uses: actions/checkout@v1
      - name: deploy docker
        run: |
          echo $GITHUB_SHA
          tag=$(git describe --tags $(git rev-list --tags --max-count=1) --abbrev=0 --always)
          echo "starting tag:${tag} docker deploy"
          docker build . --file "Dockerfile-Deploy" --tag tarscloud/gitbook:$tag
          docker push tarscloud/gitbook:$tag
